# Application name
spring.application.name=skincare

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://c3gtj1dt5vh48j.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d4en7lv32o666u
spring.datasource.username=u1b174gf07bark
spring.datasource.password=p96e0f3e91117dd93fac7391170b439f118229cfa44139dca4772db9eead12d22
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Server configuration
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:my-release-key.p12
server.ssl.key-store-password=morocaan
server.ssl.key-store-type=PKCS12
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.ssl.protocol=TLSv1.2
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

