spring.application.name=skincare

spring.jpa.show-sql=true
server.port=8443
server.ssl.key-store=/Users/macbookpro/Downloads/Embryolisse2.0-database 4/Database/skincare/skincare/src/main/resources/my-release-key.p12

server.ssl.key-store-password=morocaan
server.ssl.key-store-type=PKCS12
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3

server.ssl.protocol=TLSv1.2
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384


server.ssl.enabled=true

# PostgreSQL database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME}  # Optional, depends on your setup
spring.datasource.password=${DATABASE_PASSWORD}  # Optional, depends on your setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


