spring.application.name=skincare
spring.datasource.url=jdbc:postgresql://localhost:5432/skincare
spring.datasource.username=postgres
spring.datasource.password=4274
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
