# Remote PostgreSQL database configuration (Heroku or other remote DB)
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable Spring Security basic authentication
spring.security.basic.enabled=false

# Disable SSL in Spring Boot
server.port=${PORT:8080}  # Heroku sets the PORT environment variable
server.ssl.enabled=false