# Application name
spring.application.name=skincare

# PostgreSQL database configuration
# Database configuration
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/embryolisse}
spring.datasource.username=postgres
spring.datasource.password=morocaan



spring.datasource.driver-class-name=org.postgresql.Driver
spring.config.import=optional:env:

# Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server configuration
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=/Users/macbookpro/Downloads/Embryolisse2.0-database 4/Database/skincare/skincare/src/main/resources/my-release-key.p12
server.ssl.key-store-password=morocaan
server.ssl.key-store-type=PKCS12
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
server.ssl.protocol=TLSv1.2
server.ssl.ciphers=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

